# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_ARCH_MXC) += lec-imx8mp.dtb \
			lec-imx8mp-hydis-hv150ux2.dtb \
			lec-imx8mp-auoB101UAN01-mipi-panel.dtb \
			lec-imx8mp-wifi.dtb \
			lec-imx8mp-tlv320aic3x.dtb \
			lec-imx8mp-imx219.dtb
